name: Crypto Trading Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allow manual triggers

jobs:
  execute-trades:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.9'
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ccxt pandas pybit
        
    - name: Create log directory
      run: mkdir -p logs
        
    - name: Execute Trading Bot
      env:
        BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
        BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
      run: |
        python -u trading_bot.py 2>&1 | tee logs/execution.log
        echo "Exit code: $?" >> logs/status.txt
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trading-results-${{ github.run_number }}
        path: logs/
        retention-days: 7
