name: Trading Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  trade:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ccxt pandas pybit
    
    - name: Run trading bot
      env:
        BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
        BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
      run: python trading_bot.py
    
    - name: Upload trade state
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: trade-state
        path: trade_state.txt
